public class MessageLabel {
    public static final String SOBJECTUTIL_NOTFOUNDOBJECT   = 'Can not find specified Object : ';
    public static final String SOBJECTUTIL_NOTFOUNDFIELD    = 'Can not find specified Field : ';

    // Batch Upsert Handler 
    public static final String BATCHHANDLER_NOTFOUND_SDL    = 'Can not find SDL file in this Batch :';
    public static final String BATCHHANDLER_NOTFOUND_CSV    = 'Can not find CSV file in this Batch :';

    // CSV Handler 
    public static final String CSV_COLUMN_MISSING_TOTAL     = 'Number of Columns on this row is not equals to number of columns of header row, Line :';
    public static final String CSV_COLUMN_MISSING_EACH      = 'Can not found :';

    // TYPE CONVERTER 
    public static final String TYPE_CONVERT_INTEGER_EXCEPTION = 'Can not convert value to Integer : ';


    public static final String CUSTOM_EXCEPTION         = 'Unexpected error :';

    public static final String LOG_HEADER_CLASS         = '===================';
    public static final String LOG_HEADER_FUNCTION      = '-------------------';
}